"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { LayoutGrid, LogOut, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Tooltip, TooltipContent, TooltipTrigger, TooltipProvider } from "@/components/ui/tooltip";
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
export function UserNav() {
    return (_jsxs(DropdownMenu, { children: [_jsx(TooltipProvider, { disableHoverableContent: true, children: _jsxs(Tooltip, { delayDuration: 100, children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(DropdownMenuTrigger, { asChild: true, children: _jsx(Button, { variant: "outline", className: "relative h-8 w-8 rounded-full", children: _jsxs(Avatar, { className: "h-8 w-8", children: [_jsx(AvatarImage, { src: "#", alt: "Avatar" }), _jsx(AvatarFallback, { className: "bg-transparent", children: "JD" })] }) }) }) }), _jsx(TooltipContent, { side: "bottom", children: "Profile" })] }) }), _jsxs(DropdownMenuContent, { className: "w-56", align: "end", forceMount: true, children: [_jsx(DropdownMenuLabel, { className: "font-normal", children: _jsxs("div", { className: "flex flex-col space-y-1", children: [_jsx("p", { className: "text-sm font-medium leading-none", children: "John Doe" }), _jsx("p", { className: "text-xs leading-none text-muted-foreground", children: "johndoe@example.com" })] }) }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuGroup, { children: [_jsx(DropdownMenuItem, { className: "hover:cursor-pointer", asChild: true, children: _jsxs(Link, { href: "/dashboard", className: "flex items-center", children: [_jsx(LayoutGrid, { className: "w-4 h-4 mr-3 text-muted-foreground" }), "Dashboard"] }) }), _jsx(DropdownMenuItem, { className: "hover:cursor-pointer", asChild: true, children: _jsxs(Link, { href: "/account", className: "flex items-center", children: [_jsx(User, { className: "w-4 h-4 mr-3 text-muted-foreground" }), "Account"] }) })] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { className: "hover:cursor-pointer", onClick: () => { }, children: [_jsx(LogOut, { className: "w-4 h-4 mr-3 text-muted-foreground" }), "Sign out"] })] })] }));
}
