const sampleDrugs = [
  "Cefuroxime",
  "Ketoanalogues Essential Amino Acids",
  "Paracetamol",
  "Guaifenesin",
  "Phenylpropanolamine HCI",
  "Dextromethorphan HBR",
  "Chlorphenamine Maleate",
  "Trimetazidine",
  "Betamethasone",
  "Gentamicin",
  "Clotrim",
  "GutSkin",
  "Amlodipine",
  "Azithromycin",
  "Carbocisteine",
  "Citicoline",
  "Mupirocin",
  "Omeprazole",
  "Salbutamol",
  "Amoxicillin",
  "Ciprofloxacin",
  "Clopidogrel",
  "Fenofibrate",
  "Mefenamic Acid",
  "Vitamin B1",
  "Vitamin B6",
  "Vitamin B12",
];

export const allDrugs = [...sampleDrugs];
